# Generated by Django 3.0.6 on 2020-05-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmhouse_detail',
            name='cover_image',
            field=models.ImageField(upload_to='media/eventapp/images'),
        ),
    ]
